name: CI

on:
    push:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install deps
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Lint & test
              run: |
                  ruff check .
                  black --check .
                  pytest -q

            - name: Ensure v0.1 model exists (smoke train)
              run: |
                  [ -f models/v0.1/model.joblib ] || python training/train_v01.py

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: v01-artifacts
                  path: |
                      models/v0.1/model.joblib
                      models/v0.1/metrics.json
